#server port
server:
  port: 8080
  
#JSP
spring:
  -mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  -datasource:
        url: jdbc:mysql://localhost:3306/mydb?serverTimezone=Asia/Seoul
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
  -servlet:
    multipart:
      max-file-size: 5MB

##MyBatis
mybatis:
  config-location: classpath:mybatis-config.xml
  type-aliases-package: user.bean
  mapper-locations: classpath:mapper/**/*.xml